#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
#
services:
  xpanse:
    container_name: xpanse
    image: ghcr.io/eclipse-xpanse/xpanse:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TERRA_BOOT_WEBHOOK_ENDPOINT=http://xpanse:8080
      - TOFU_MAKER_WEBHOOK_ENDPOINT=http://xpanse:8080
      - TERRA_BOOT_ENDPOINT=http://terra-boot:9090
      - TOFU_MAKER_ENDPOINT=http://tofu-maker:9092
      - AUTHORIZATION_TOKEN_TYPE=JWT
      - SPRING_DATASOURCE_URL=jdbc:otel:mysql://db:3306/xpanse
      - SPRING_ACTIVITI_DATASOURCE_URL=jdbc:otel:mysql://db:3306/activiti
      - SPRING_PROFILES_ACTIVE=oauth,zitadel,zitadel-testbed,terra-boot,tofu-maker,mysql,redis,opentelemetry,dev
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver
      - SPRING_ACTIVITI_DATASOURCE_DRIVER_CLASS_NAME=io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver
      - POLICY_MAN_ENDPOINT=http://policy-man:8090
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - SPRING_DATASOURCE_USERNAME=xpanse
      - SPRING_ACTIVITI_DATASOURCE_USERNAME=activiti
      - SPRING_REDIS_HOST=xpanse-redis
      - PLUS_SERVER_AUTH_URL=https://api.gx-scs.sovereignit.cloud:5000/v3
      - REGIO_CLOUD_AUTH_URL=https://keystone.services.a.regiocloud.tech
      - OPENSTACK_TESTLAB_AUTH_URL=http://119.8.215.244/identity/v3
    env_file:
      - .xpanse.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/v3/api-docs" ]
      interval: 30s
      timeout: 120s
      retries: 5

  ui:
    container_name: ui
    image: ghcr.io/eclipse-xpanse/xpanse-ui:latest
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_ZITADEL_AUTHORITY_URL=https://iam.xpanse.site
      - VITE_APP_ZITADEL_CLIENT_ID=293850493212491779@eclipse-xpanse
      - VITE_APP_XPANSE_API_URL=https://demo.xpanse.site
      - VITE_APP_AUTH_DISABLED=false
      - VITE_APP_AUTH_USE_SERVICE_WORKER_ONLY=true
    depends_on:
      xpanse:
       condition: service_healthy

  db:
    container_name: db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=xpanse
      - MYSQL_USER=xpanse
    env_file:
      - .mysql.db.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    container_name: redis
    image: redis:latest
    env_file:
      - .redis.env
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  terra-boot:
    container_name: terra-boot
    image: ghcr.io/eclipse-xpanse/terra-boot:latest
    ports:
      - "9090:9090"
    environment:
      - LOG_TERRAFORM_STDOUT_STDERR=true
      - TERRAFORM_ROOT_MODULE_DIRECTORY=/tmp/terra-boot
      - SPRING_PROFILES_ACTIVE=dev,opentelemetry
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9090/v3/api-docs" ]
      interval: 30s
      timeout: 10s
      retries: 5

  tofu-maker:
    container_name: tofu-maker
    image: ghcr.io/eclipse-xpanse/tofu-maker:latest
    ports:
      - "9092:9092"
    environment:
      - LOG_TERRAFORM_STDOUT_STDERR=true
      - OPENTOFU_ROOT_MODULE_DIRECTORY=/tmp/tofu-maker
      - SPRING_PROFILES_ACTIVE=dev,opentelemetry
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9092/v3/api-docs" ]
      interval: 30s
      timeout: 10s
      retries: 5

  policy-man:
    container_name: policy-man
    image: ghcr.io/eclipse-xpanse/policy-man:latest
    command: --host=0.0.0.0
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8090/swagger/doc.json" ]
      interval: 30s
      timeout: 10s
      retries: 5

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    ports:
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
    restart: always
    command:
      - --config=/etc/otelcol-cont/otel-collector.yml
    volumes:
      - ./collector/otel-collector-grafana-stack.yml:/etc/otelcol-cont/otel-collector.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
      - GF_SERVER_SERVER_FROM_SUB_PATH=true

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
    ports:
      - "4317"  # otlp grpc

  loki:
    container_name: loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml

  go-auto:
    depends_on:
      - policy-man
    image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:latest
    privileged: true
    pid: "host"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_GO_AUTO_TARGET_EXE=/usr/bin/policy-man
      - OTEL_GO_AUTO_INCLUDE_DB_STATEMENT=true
      - OTEL_SERVICE_NAME=policy-man
      - OTEL_PROPAGATORS=tracecontext,baggage
      - CGO_ENABLED=1
    volumes:
      - /proc:/host/proc
    container_name: policy-man-auto-instrumentation